//
// Created by cc on 2018/11/16.
//

#ifndef STALK_V2_UIPICTUREBROWSER_GLOBAL_H
#define STALK_V2_UIPICTUREBROWSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UIPICTUREBROWSER_LIBRARY)
#  define UIPICTUREBROWSER_EXPORT Q_DECL_EXPORT
#else
#  define UIPICTUREBROWSER_EXPORT Q_DECL_IMPORT
#endif

#endif //STALK_V2_UIPICTUREBROWSER_GLOBAL_H
